language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - pip install --use-mirrors --upgrade pytest>=2.4 ./
script: 
  - ./runtests.sh
notifications:
  email: false
branches:
  only:
    - master
